'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { AuthUser, clearAuth, getUser } from '@/lib/auth-client';

const baseLinks=[{href:'/',icon:'▦',label:'Knowledge Feed'},{href:'/write',icon:'＋',label:'게시물 올리기'}];
export default function Header(){
  const pathname=usePathname(); const router=useRouter(); const[user,setUser]=useState<AuthUser|null>(null);
  useEffect(()=>{const sync=()=>setUser(getUser());sync();window.addEventListener('auth-change',sync);return()=>window.removeEventListener('auth-change',sync)},[]);
  const conversationLink={href:'/conversations',icon:'▤',label:'지식창고와의 대화'};
  const userLinks=user?[...baseLinks,conversationLink]:baseLinks;
  const links=user?.role==='ROLE_ADMIN'?[...userLinks,{href:'/admin/categories',icon:'⌘',label:'주제 관리'}]:userLinks;
  const topLinkClass=(href:string)=>{const active=href==='/'?pathname==='/':pathname.startsWith(href);return `flex h-full items-center border-b-2 ${active?'border-[#002045] font-bold text-[#002045]':'border-transparent text-[#545f72] hover:text-[#002045]'}`};
  function logout(){clearAuth();router.push('/');router.refresh()}
  return <><aside className="desktop-sidebar fixed inset-y-0 left-0 z-30 flex w-[280px] flex-col border-r border-[#c4c6cf] bg-[#f2f4f6] p-5"><Link href="/" className="mb-10 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[3px] border border-[#002045] bg-[#1a365d] text-xl text-white">▣</span><span><b className="block text-xl tracking-wide text-[#002045]">Knowledge Hub</b><small className="mono text-[11px] text-[#545f72]">{user?`${user.username} · ${user.role.replace('ROLE_','')}`:'GUEST SESSION'}</small></span></Link><Link href="/#ai-search" className="btn-ai mb-6 flex items-center justify-center gap-2 mono text-sm">✦ AI ASSISTANT</Link><nav className="space-y-1">{links.map(link=>{const active=link.href==='/'?pathname==='/':pathname.startsWith(link.href);return <Link key={link.href} href={link.href} className={`flex items-center gap-3 rounded-[4px] px-3 py-2.5 text-sm font-semibold ${active?'bg-[#d5e0f7] text-[#1a365d]':'text-[#545f72] hover:bg-[#e6e8ea]'}`}><span className="w-5 text-center text-lg">{link.icon}</span><span className="mono">{link.label}</span></Link>})}</nav><div className="mt-auto border-t border-[#c4c6cf] pt-4">{user?<button onClick={logout} className="w-full px-3 py-2 text-left mono text-sm text-[#545f72]">로그아웃</button>:<Link href="/auth" className="block px-3 py-2 mono text-sm font-bold text-[#1a365d]">로그인</Link>}</div></aside><header className="portal-top fixed left-[280px] right-0 top-0 z-20 flex h-16 items-center justify-between border-b border-[#c4c6cf] bg-white px-8"><Link href="/" className="text-xl font-bold tracking-tight text-[#002045]">KNOWLEDGE HUB</Link><nav className="top-links flex h-full items-center gap-8 text-sm"><Link className={topLinkClass('/')} href="/">Dashboard</Link>{user&&<Link href="/write" className={topLinkClass('/write')}>Publish</Link>}{user?.role==='ROLE_ADMIN'&&<Link href="/admin/categories" className={topLinkClass('/admin')}>Admin</Link>}</nav><div className="flex items-center gap-3">{user?<><span className="mono text-xs text-[#455f88]">{user.username}</span><button onClick={logout} className="btn-secondary text-xs">Logout</button></>:<Link href="/auth" className="btn-primary text-xs">Login</Link>}</div></header></>;
}
